sonar.projectKey=yuto-omi_web-task-backend
sonar.organization=yuto-omi

sonar.sources=app
sonar.tests=tests
sonar.exclusions=vendor/**,storage/**,bootstrap/**,database/**,public/**

sonar.php.coverage.reportPaths=coverage.xml
