server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;

    client_max_body_size 2G; 

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        root /var/www/html/public;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, Origin' always;

        # Se precisar de preflight request
        if ($request_method = OPTIONS) {
            return 204;
        }
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
